# Generated by Django 4.2.2 on 2023-07-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie_curses',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
