# Generated by Django 4.2.2 on 2023-07-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_categorie_curses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie_curses',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
