# Generated by Django 4.2.1 on 2023-07-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_courses_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='categorie_couse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.categorie_curses'),
        ),
    ]
