# Generated by Django 4.2.1 on 2023-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_courses_categorie_couse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='categorie_couse',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
