# Generated by Django 4.2.1 on 2023-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_courses_categorie_couse'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
