# Generated by Django 4.2.2 on 2023-07-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_alter_courses_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='friens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_1', models.IntegerField()),
                ('friend_2', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='image',
        ),
        migrations.AddField(
            model_name='courses',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
