# Generated by Django 4.2.2 on 2023-07-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_friens_remove_courses_image_courses_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
