# Generated by Django 4.2.2 on 2023-07-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_rename_active_categorie_curses_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie_curses',
            name='delete',
        ),
    ]
