# Generated by Django 4.2.2 on 2023-07-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_remove_categorie_curses_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie_curses',
            name='delete',
            field=models.BooleanField(default=True),
        ),
    ]
