# Generated by Django 4.2.2 on 2023-07-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_categorie_curses_delete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='friens',
            new_name='friends',
        ),
    ]
