# Generated by Django 4.2.2 on 2023-07-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_rename_categorie_couse_courses_categorie_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorie_curses',
            new_name='categorie_course',
        ),
    ]
