# Generated by Django 4.2.2 on 2023-07-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_rename_categorie_curses_categorie_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friends',
        ),
    ]
